final data = {
  "status": "success",
  "message": "Products retrieved successfully",
  "user": {"id": 1, "name": "ahmad", "user_name": 'ah13'},
  "products": [
    {
      "id": "prod_001",
      "name": "Wireless Bluetooth Headphones",
      "price": 79.99,
      "currency": "USD",
      "category": "Electronics",
      "stock": 42,
      "in_stock": true,
      "image": "https://example.com/images/headphones.jpg",
    },
    {
      "id": "prod_002",
      "name": "Smart Watch Pro",
      "price": 129.99,
      "currency": "USD",
      "category": "Wearables",
      "stock": 18,
      "in_stock": true,
      "image": "https://example.com/images/smart-watch.jpg",
    },
    {
      "id": "prod_003",
      "name": "Mechanical Gaming Keyboard",
      "price": 64.99,
      "currency": "USD",
      "category": "Computer Accessories",
      "stock": 7,
      "in_stock": true,
      "image": "https://example.com/images/gaming-keyboard.jpg",
    },
    {
      "id": "prod_004",
      "name": "Wireless Gaming Mouse",
      "price": 39.99,
      "currency": "USD",
      "category": "Computer Accessories",
      "stock": 0,
      "in_stock": false,
      "image": "https://example.com/images/gaming-mouse.jpg",
    },
  ],
};
